Jakefile: Fix module error while building.
Problem: "Error: Cannot find module 'mocha'" occurs when execute
"jake build" if mocha is not installed.

Solution: Require 'mocha' if and only if run tests.